services:

  api:
    build:
      context: ./backend/src/
      dockerfile: TradingSim.Api/Dockerfile
    ports:
      - "7001:8080"
    container_name: tradingsim-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    container_name: tradingsim-frontend
    depends_on:
      - api